version: 0.2

phases:
  install:
    commands:
    # printenv
    # pwd
    - mkdir -p /go/src/github.com/weAutomateEverything/snmpHal
    - cp -R * /go/src/github.com/weAutomateEverything/snmpHal/
  pre_build:
    commands:

    finally:

  build:
    commands:
    - go get github.com/weAutomateEverything/snmpHal
    - GOOS=linux CGO_ENABLED=1 go build -ldflags '-linkmode=external' -o ./snmpHal github.com/weAutomateEverything/snmpHal
    -
  post_build:
    commands:
    - aws s3 cp ./snmpHal "s3://snmphal/snmpHal" --acl public-read

    finally:

artifacts:
  files:
  - snmpHal
cache:
  paths:
